# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Configure NPM
      run: |
        npm config set "@fortawesome:registry" https://npm.fontawesome.com/
        npm config set '//npm.fontawesome.com/:_authToken' "${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}"
    - name: Restore dependencies
      working-directory: ./src
      run: dotnet restore
    - name: Build
      working-directory: ./src
      run: |
        dotnet build -c Release --no-restore
        dotnet publish -c Release
    - uses: actions/upload-artifact@v3
      with:
        name: Web-UI
        path: 'src/EDOverwatch Web/bin/Release/net7.0'
    - uses: actions/upload-artifact@v3
      with:
        name: EDDataProcessor
        path: 'src/EDDataProcessor/bin/Release/net7.0'
    - uses: actions/upload-artifact@v3
      with:
        name: EDDNClient
        path: 'src/EDDNClient/bin/Release/net7.0'
    - uses: actions/upload-artifact@v3
      with:
        name: EDOverwatch
        path: 'src/EDOverwatch/bin/Release/net7.0'
        
